# Generated by Django 5.2.7 on 2025-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('horchata', 'Horchata'), ('cardamomo', 'Cardamomo'), ('lavanda', 'Lavanda'), ('coldbrew', 'Coldbrew'), ('matcha', 'Matcha'), ('maple', 'Maple')], max_length=20)),
                ('volumen_ml', models.PositiveIntegerField(default=295)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
